<?php

/**
 * Implements hook_menu().
 */
function test_demo_menu() {
  $items = array();

  $items['test_demo_access/%'] = array(
    'title' => 'Test demo access',
    'description' => 'Test callback for test_demo module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('test_demo_access_form', 1),
    'access callback' => 'test_demo_access',
    'access arguments' => array(1),
  );

  return $items;
}

/**
 * @param string $access
 *
 * @return string
 */
function test_demo_access_form($form, &$form_state, $access) {
  $form['header'] = array(
    '#markup' => '<h1 id="test-demo-title">' . format_string('Access: @access', array('@access' => $access)) . '</h1>',
  );

  $form['test_link'] = array(
    '#type' => 'link',
    '#title' => t('Test link'),
    '#href' => url('user', array('absolute' => TRUE)),
  );

  $form['test_form_element'] = array(
    '#type' => 'textfield',
    '#title' => t('Test value'),
    '#default_value' => 123,
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save form'),
  );

  return $form;
}

/**
 * Submit handler for test_demo_access_form().
 */
function test_demo_access_form_submit($form, &$form_state) {
  drupal_set_message(format_string('Test value is @value.', array('@value' => $form_state['values']['test_form_element'])));
  $form_state['redirect'] = 'user';
}

/**
 * @param string $access
 *
 * @return bool
 */
function test_demo_access($access) {
  switch ($access) {
    case 'yes':
      return TRUE;
    case 'no':
    default:
      return FALSE;
  }
}
